### ISSUE TITLE
Anhang mitversenden?

### ISSUE THREAD

**Issue by rotzek** [TobiasKrais/multinewsletter#11]
Gibt es eine Möglichkeit, einen Anhang (pdf-Dokument) mitzuversenden?

**Comment by TobiasKrais** [comment]
Nein. Den müsstest du verlinken. Bei Newslettern mit einem Anhang erhöht sich die Gefahr als Spam erkannt zu werden signifikant.

**Comment by rotzek** [comment]
Das müsste aber der Versender doch selber entscheiden können/dürfen, oder? Ich habe aktuell den Fall, dass wöchentlich ein automatisch erzeugter Speiseplan an Kunden einer Metzgerei geschickt werden soll, da brauche ich das unbedingt...

**Comment by TobiasKrais** [comment]
Ja, da hast du Recht. Hast du die Möglichkeit da was zu programmieren und per Pull Request zu schicken?

**Comment by rotzek** [comment]
nicht wirklich, meine PHP Kenntnisse erstrecken sich auf Code verstehen (einigermaßen), Skripte zusammenfügen, und kleinere Dinge ohne OO :-( Ich bräuchte das in ca. 8 Wochen erst, vielleicht wäre das ein Feature... Wäre auch bereit, dafür etwas zu "spenden"!

**Comment by TobiasKrais** [comment]
Tom, du kannst mich über meine Webseite kontaktieren: https://www.design-to-use.de/. Dann können wir das besprechen.

**Comment by TobiasKrais** [comment]
Möglichkeit gibt es schon.
