### ISSUE TITLE
Doppelte Domain Links

### ISSUE THREAD

**Issue by paddle07** [TobiasKrais/multinewsletter#12]
Hallo Tobias
Beim Versand eines Artikels via Multinewsletter kommt es beim Kunden vor, dass die Links eine doppelte Domain enthalten und daher die Seite nicht geöffnet werden kann. Beispiel:
Aus https://www.domain.ch/link-zum-artikel/ wird https://www.domain.chhttps//www.domain.ch/link-zum-artikel/
Wenn ich den Versand starte sehen die Links gut aus. Die Links hole ich via rex_getUrl(id). Hast du eine Idee woran das liegen kann?

**Comment by TobiasKrais** [comment]
Das ist eine gute Frage. Ich brauche noch ein paar Infos von dir:
- Welcher Link steht im Quelltext des Artikels? Hast du eventuell einen Beispiellink zum Aritkel?
- Gibt es einen einen base Tag?
- Nutzt du YRewrite?
- Was bedeutet "kommt es vor". Tritt der immer auf oder nur manchmal? Wenn es manchmal ist: was unterscheidet den Link bei dem es funktioniert von dem, bei dem es nicht funktioniert?

**Comment by paddle07** [comment]
Es kommt nicht immer vor... mit meinem Computer klappt alles wie es soll und beim Kunden hat es mit einem Computer funktioniert und mit einem anderen ist der Bug immer wieder aufgetreten.

Wenn der Artikel direkt aufgerufen wird, stimmen alle Links, danach im Mail nicht mehr.

- Kein Base-Tag
- Ja, nutze YRewrite

Es passiert nur mit den Links zu einem Artikel, die Links zu den assets verändern sich z.B. nicht.

**Comment by paddle07** [comment]
Hier der Link des letzten Newsletter Artikel:
https://www.meinegesundheit-online.ch/info/newsletter/newsletterartikel/2018/februar-2018-nr-2/ <https://www.meinegesundheit-online.ch/info/newsletter/newsletterartikel/2018/februar-2018-nr-2/>

**Comment by TobiasKrais** [comment]
Ich melde mich noch. Den Fehler konnte ich noch nicht lokalisieren.

**Comment by TobiasKrais** [comment]
Seltsam. Den Newsletter habe ich mir angesehen. Sieht gut aus - nicht nur die Links, sonder auch die Seite ;-). Was steht bei dir in Redaxo unter System -> "URL der Website"? Ist das die URL inkl. https:// drin? Auch in den Einstellungen deiner Domain von YRewrite: steht das das https:// auch mit drin?

Welche Links sind von dem Fehler betroffen? Nur der "Im Browser ansehen" und "Newsletter abmelden"? Oder nur Links im Text? Oder beide?

**Comment by paddle07** [comment]
Danke ;) Die Url unter System und YRewrite sind identisch (inkl. https), habe da auch schon verschiedene Einstellungen ausprobiert. Ist vor allem komisch, dass es nicht auf allen Computern der Fall ist… kann es mir auch nicht erklären.

**Comment by TobiasKrais** [comment]
Welche Links sind von dem Fehler betroffen? Nur der "Im Browser ansehen" und "Newsletter abmelden"? Oder nur Links im Text? Oder beide?

**Comment by paddle07** [comment]
alle links zu einem artikel… im browser ansehen, newsletter abmelden, zum artikel

**Comment by TobiasKrais** [comment]
OK. Also alle Redaxo internen Links. Ich habe keine Ahnung wie das kommt. Bitte gib mir Bescheid, wenn du eine Methode hast um den Fehler gezielt zu reproduzieren. Bis dahin lasse ich den Issue mal offen.

**Comment by TobiasKrais** [comment]
Ich glaube ich habe den Fehler gefunden. Kannst du die geänderte Datei bei dir auf dem Server mal austauschen und dann schauen, ob es besser ist?

**Comment by TobiasKrais** [comment]
Wird in 3.1.7 behoben sein.
