### ISSUE TITLE
Signup nur per Mail

### ISSUE THREAD

**Issue by cukabeka** [TobiasKrais/multinewsletter#13]
Das Szenario, Vor-, Nachname und Anrede als Pflichtfeld zu haben, sehe ich für einen Newsletter eher als Ausnahme. Fände es sehr hilfreich, wenn Multinewsletter per Default auch einen Signup nur mit E-Mail als einziger Angabe ermöglichen würde.

**Comment by TobiasKrais** [comment]
Ja, das ist eine gute Idee. Du kannst das Modul einfach für dich anpassen. Es ist als Beispiel gedacht.

**Comment by cukabeka** [comment]
Ich hatte enorme Probleme, die Filter zu umgehen, ohne mich in den Addon-code einzulesen. Habe es am Ende nur mit hidden input fields hinbekommen. Fände hilfreich, wenn es evtl 2 Varianten gibt oder eine kleine Doku, wie die Filter funktionieren, wenn ich ein Feld ausbauen möchte.

**Comment by TobiasKrais** [comment]
Ab der nächsten Version gibt des das Modul 80-3 für eine Anmeldung mit "E-Mail only". Im obigen commit kannst du dir das jetzt schon runterladen.
