### ISSUE TITLE
Felddefinitionen bei Sprache mit Defaults füllen

### ISSUE THREAD

**Issue by cukabeka** [TobiasKrais/multinewsletter#14]
Fände sehr hilfreich fürs Setup, wenn es Standardwerte für die Felddefinitionen wenigstens in deutsch gäbe. So muss ich sehr viel raten, wie was gemeint ist - und wenn ich das Addon in mehreren REX-Instanzen einsetze, wird das Setup sehr aufwändig.

**Comment by TobiasKrais** [comment]
Meinst du in den Einstellungen? Da gibt es bei den Sprachen jeweils rechts oberhalb das grüne Feld "Presets". Oder meinst du etwas anderes?

**Comment by cukabeka** [comment]
Uaah, voll übersehen 😱 
Evtl ist das sichtbarer, wenn es nicht rechtsbündig angeordnet ist, sondern als separate Zeile direkt am Anfang!
- Aber ja, genau sowas meinte ich! ;)
