### ISSUE TITLE
Beim anmelden im Newsletter Fehlermeldung

### ISSUE THREAD

**Issue by jeje-993** [TobiasKrais/multinewsletter#16]
Hallo Tobias,

ich habe heute den MultiNewsletter Version 3.1.3 installiert, bekomme aber beim anmelden ein Fehler im Modul angezeigt 
` rex:///module/25/output
 
 "Call to a member function getId() on boolean"

Error
rex:///module/25/output59 `

leider kann ich den Fehler nicht nachvollziehen.

Gruß
Jochen

**Comment by TobiasKrais** [comment]
Ist der Fehler in Version 3.1.6 noch vorhanden?

**Comment by TobiasKrais** [comment]
Geschlossen wegen mangelnder Rückmeldung.
