### ISSUE TITLE
default / fallback language wieder ins Addon verschieben

### ISSUE THREAD

**Issue by palber** [TobiasKrais/multinewsletter#17]
Benötige die Funktion die Fallback-Language-Id auch auf null zu setzen, sprich die Fallback-Funktion zu deaktivieren.

Habe gesehen, dass die Einstellung ins d2u-helper addon verschoben worden ist [[commit](https://github.com/TobiasKrais/multinewsletter/commit/f4f8addfef40c584a44a793f265624551eada49a#diff-a12673c823cc1693b55ab1b414d2e1a7)]

Wollte fragen ob diese Einstellung nur für das Multinewsletter-Fallback-Language gedenkt ist - oder auch für andere Dinge verwendet wird.

Ich finde folgende Lösungsansätze möglich:
1) man trennt/markiert die Einstellung explizit für Multinewsletter
2) Finde es sinnvoller diese Einstellung ins Multinewsletter-Addon zu verschieben und dort zu behalten, da diese Einstellung unabhängig von anderen sein sollte

und dann mit einer Option zu erweiteren, die Fallback-Language auch auf null zu setzen.

Bin offen für eine kurze Diskussion und kann es dann gerne entsprechend anpassen.

**Comment by TobiasKrais** [comment]
Sorry, dass ich mich erst jetzt melde. Die Benachrichtigung ist als Spam abgelehnt worden.

Die Default Lang Fallback wird von nahezu allen anderen meiner Addons genutzt. Das ist der Hintergrund der Verschiebung.

Was ist denn dein Szenario?

**Comment by palber** [comment]
Ich möchte im multinewsletter das Fallback deaktivieren. also das wenn der Artikel offline ist der User auch keine Mail erhaltet.

Deswegen bin ich der Meinung man sollte den Fallback beim Newsletter getrennt von einem evt. anderen Fallback verwenden. Daraus ergeben sich auch meine 2 Lösungsvorschläge oben.

**Comment by TobiasKrais** [comment]
Das macht Sinn, da hast du recht. Wie wäre es mit einer Einstellung mit folgenden Optionen:
- Sprachfallback deaktivieren
- Sprachfallback aus den Einstellungen des D2U Helper Addons benutzen

**Comment by palber** [comment]
Klingt gut!

Ich kann gerne einen PR dazu vorbereiten - hoffe ich komme demnächst dazu.

**Comment by TobiasKrais** [comment]
Sehr gerne. Gib Bescheid. Vielleicht komme ich auch dazu etwas zu machen. Danke für deine Hilfe!

**Comment by TobiasKrais** [comment]
Danke nochmals! Kann ich den Issue schließen?

**Comment by palber** [comment]
Danke dir! Ich schließe den Issue da somit abgeschlossen.
