### ISSUE TITLE
Iconprobleme mit aktivierten Multinewsletter

### ISSUE THREAD

**Issue by spiritandsoul** [TobiasKrais/multinewsletter#21]
Hallo Tobias,
Ich lade für meine Webseite die Fonts von "Fontello" allerdings habe ich das Problem, wenn ich den Multinewsletter aktiviere , dass es mir die Icons nicht mehr anzeigt. Hättest Du da ne Idee zu ?????

LG Christian :-)
![screen1](https://user-images.githubusercontent.com/34594030/41353374-61ff6dde-6f1c-11e8-9954-8bcb4bb1dae7.jpg)
![screen2](https://user-images.githubusercontent.com/34594030/41353375-622a9036-6f1c-11e8-824b-c6f09f198838.jpg)

**Comment by TobiasKrais** [comment]
Hi Christian,
Ich könnte mir schon denken wo der Haken liegt. Kannst du mal versuchen den Fix oben auszuprobieren? Wird es dann besser?
Bitte gib Bescheid.
LG, Tobi

**Comment by spiritandsoul** [comment]
Hey Tobi, ich weiß zwar nicht ob ich es richtig gemacht hab, die drei Zeilen zu tauschen.
Hab ich gemacht, Cache geleert aber leider keine Besserung.
Danke für deine Hilfe, Tobi
LG

**Comment by TobiasKrais** [comment]
Ja, es betrifft nur die 3 Zeilen. Das hast du richtig gemacht. Kannst du mir bitte den Quelltext der Icons posten. Falls ein CSS dazugehört bitte auch den relevanten CSS Teil.

**Comment by spiritandsoul** [comment]
<i class="icon-home"></i>

.icon-home:before{content:'e812'}

@font-face{font-family:'fontello';src:url(http://new.christianhass.com/resources/fonts/fontello.eot);src:url(http://new.christianhass.com/resources/fonts/fontello.eot#iefix) format("embedded-opentype"),url(http://new.christianhass.com/resources/fonts/fontello.woff2) format("woff2"),url(http://new.christianhass.com/resources/fonts/fontello.woff) format("woff"),url(http://new.christianhass.com/resources/fonts/fontello.ttf) format("truetype"),url(http://new.christianhass.com/resources/fonts/fontello.svg#fontello) format("svg");font-weight:400;font-style:normal}[class^="icon-"]:before,[class*=" icon-"]:before{font-family:"fontello";font-style:normal;font-weight:400;speak:none;display:inline-block;text-decoration:inherit;width:1em;margin-right:.2em;text-align:center;font-variant:normal;text-transform:none;line-height:1em;margin-left:.2em;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale}

**Comment by TobiasKrais** [comment]
Hmm. Da sieht noch alles gut aus. Entspricht der Quellcode der Testmail genau dem was du mir geschickt hast oder sieht der ein wenig anders aus?

**Comment by spiritandsoul** [comment]
Hey Tobi, soweit bin ich noch nicht. Das Aktivieren vom Multinewsletter zerschiesst Icons auf der Webseite, hätte ich vielleicht direkt mit beischreiben sollen. Hab ich nicht dran gedacht. Weiter bin ich noch nicht im Aufbau. Zu sehen unter: test. christianhass .com...

**Comment by spiritandsoul** [comment]
Beim aktiven, wie inaktiven Addon ändert sich nichts im Quelltext. Alles noch und nöcher überprüft. Die Konsole spuckt nichts aus. Keine CSS-Fehler laut W3C. Das gleiche Problem ist auch mit Themify Icons da. Leider kann ich nicht festellen ob es rein vom Multinewsletter oder vom Helper-Addon kommt, da eine Abhängigkeit besteht.

**Comment by TobiasKrais** [comment]
Das ist ja Mega interessant. Mit ziemlicher Sicherheit hängt das vom D2U Helper Addon ab. Kannst du bitte mal versuchen in den Einstellungen des Addons alle Haken zu deaktiveren? Was passiert dann?

**Comment by spiritandsoul** [comment]
Da ich Foundation als Framework nutze ist für mich das Helper-Addon nicht wirklich nutzbar. Weder beim Multinewsletter oder Helper waren und sind keine Häkchen gesetzt. Habe einfach nur die Addons aktiviert und dann kam der Fehler das die Icons nicht mehr gezeigt wurden.... Würde gern weiterkommen. Aber ich bin so ratlos damit....

**Comment by TobiasKrais** [comment]
Mein Chrome bringt eine Fehlermeldung. Aber die Icons werden angezeigt.
![2018-06-14](https://user-images.githubusercontent.com/4131072/41411654-da9ca3c6-6fdd-11e8-8dc3-6d3cd3367e4f.png)

**Comment by spiritandsoul** [comment]
Du bist auf der falschen Domain gewesen: new.christianhass.com ist die Domain wo der Fehler ist...

**Comment by spiritandsoul** [comment]
So konnte es noch weiter eingrenzen, der Fehler tritt mit der Version 3.1.1 ein. Im Changelog steht das Du alles von SEO42 entsorgt hast. Ich glaube da sitzt mein Fehler. Ich nutze von Xcore von Rudi. Hast Du SEO42 nur im Template entsorgt????

**Comment by TobiasKrais** [comment]
SEO42 hatte ich im Template entsorgt. Sonst wird es nicht verwendet. Ich schaue mir später noch die Seite genauer an und melde mich.

**Comment by TobiasKrais** [comment]
Also was mir im Unterschied der beiden Seiten auffällt ist, das CSS:
`.icon-pinterest-circled:before {
    content: 'f0d2';
}`
Auf der Seite, Auf der es nicht funktioniert ist der Code wie oben. Es fehlt der `\` zu Beginn des contents. Ist das im Originalcode auch so? Was passiert, wenn du das CSS in eine Datei auslagerst?

**Comment by spiritandsoul** [comment]
Ich glaube wir kommen der Sache näher:
Im Template wird es richtig angezeigt: .icon-pinterest-circled:before { content: '\f0d2'; } Mit aktivierten MN verschwindet das umgedrehte Slashzeichen. Ich weiß gar nicht wie es heißt. Da hab ich dann schon stundenlang drauf geschaut und doch nicht gesehen das sich was ändert, menno.... Also wenn ich die CSS auslagere geht es erstmal....

**Comment by TobiasKrais** [comment]
Ja, ich denke wir kommen der Sache näher. Ich vermute, dass der Fehler durch einen Pull Request gekommen ist, den ich nicht geprüft habe. Dazu wird der OutputFilter bemüht. Kannst du wie bei dem Commit oben die `stripslashes()` Methode entfernen und mal probieren was dann passiert? Funktioniert der Newsletter dann überhaupt noch korrekt?

**Comment by spiritandsoul** [comment]
Mit dem Code wird alles korrekt angezeigt. Gib mir ein paar Tage Zeit dann weiß ich ob alles andere vom Multinewsletter auch schnaggelt... Ich setze eine meiner Seiten neu auf, weg von Wordpress. Mit Redaxo kann ich in allem punktgenauer arbeiten. ;-)

**Comment by TobiasKrais** [comment]
Das hört sich gut an. Danke schon mal fürs erste Feedback. Ich lass den Issue mal auf bis ich wieder von dir höre. Danke!

**Comment by spiritandsoul** [comment]
Hey Tobi, die Newsletterfunktionen funktionieren soweit, konnte keinen Fehler erkennen.
Danke für deine Hilfe Tobi. :-)

**Comment by TobiasKrais** [comment]
Danke für deine Hilfe!
