### ISSUE TITLE
Modul-Bug, wenn Mailadresse fehlt

### ISSUE THREAD

**Issue by cukabeka** [TobiasKrais/multinewsletter#22]
Mini-Bug, hatte ich mal entdeckt. Blicke aber nicht durch, wie ich hier einen PR dazu machen kann: https://github.com/raum2projekt/multinewsletter/commit/ca89f8a8a234db6da8cad7cdc82160838bc3388e

**Comment by TobiasKrais** [comment]
Das Projekt von raum2projekt war der MultiNewsletter für Redaxo 4. Der Support für Redaxo 4 ist von meiner Seite eingestellt, da hier auch Anpassungen an die DSGVO nötig wären. Bist du dir sicher, dass du in der Version noch was anpassen wolltest?

**Comment by cukabeka** [comment]
Oh, das hatte ich übersehen, dass das der alte MNL ist - war nur etwas verwirrt. Dann kann das hier weg ;)
