### ISSUE TITLE
Sync mit anderen Newsletterprovidern als Mailchimp

### ISSUE THREAD

**Issue by cukabeka** [TobiasKrais/multinewsletter#23]
DSGVO lässt grüßen. ;)
Evtl Cleverreach oder Newsletter2go. Für ersteres gibts auch ein Addon, wo sich was abschauen lässt.

**Comment by TobiasKrais** [comment]
Weitere Anbindungen gerne als Pull Request. Der Code für MailChimp wurde mir beigesteuert.

Die Hilfe und die Einstellungen habe ich um einen DSGVO Hinweis ergänzt.
