### ISSUE TITLE
Newsletterversand via IFTTT anstoßen

### ISSUE THREAD

**Issue by cukabeka** [TobiasKrais/multinewsletter#24]
Hi, 

ich möchte die Möglichkeit bauen, den Newsletter via IFTTT/Webrequest anzustoßen und suche dazu etwas im Code, wo der Mailversand angestoßen wird und ob es möglich ist, das einfach per Funktion aus einer anderen Funktion aufzurufen. 

Das hier habe ich gefunden:
https://github.com/TobiasKrais/multinewsletter/blob/b229eb8ea1cf36657bac918db654dafed55b643f/lib/multinewsletter_newsletter.php#L383

Aber ich finde nichts, was den eigentlichen Versand anstößt. Kannst Du mir hier weiterhelfen?

Viele Grüße

**Comment by TobiasKrais** [comment]
Hier hast du einen Einstiegspunkt und siehst auch gleich wie er verwendet wird: https://github.com/TobiasKrais/multinewsletter/blob/b229eb8ea1cf36657bac918db654dafed55b643f/pages/newsletter.php#L251

**Comment by cukabeka** [comment]
Danke, damit bin ich schon etwas weitergekommen, aber es hängt noch an 2 Punkten. 

1. Konzeptionell: Im Prinzip braucht es ja einen Cronjob, um die Funktion regelmäßig aufzurufen, bis alle Mails versendet sind. Bin mir noch nicht klar, wie ich das erreiche, wenn von außen ein Trigger kommt. Idee ist ja, einen neuen Newsletter zu versenden, wenn ein RSS Feed einen neuen Eintrag hat. IFTTT kann das ganz gut.

2. Code. Ich habe also direkt im Cronjob Addon herumprobiert, ob sich ein Mailversand anstoßen lässt. Ergebnis: Das Skript wird zwar ausgeführt, aber es kommt noch keine Mail an. 

```
<?php

$group_ids = array(2);
$article_id = 120;
$fallback_clang_id = MultinewsletterNewsletter::getFallbackLang();
$man_recipients = array();
$addon = rex_addon::get('multinewsletter');

dump(rex_config::get('podcastmanager', 'max_mails'));

$newsletterManager = new MultinewsletterNewsletterManager(rex_config::get('podcastmanager', 'max_mails'), rex::getTablePrefix());

$newsletterManager->prepare($group_ids, $article_id, $fallback_clang_id,$man_recipients);

	$number_mails_send = $newsletterManager->countRemainingUsers() % $addon->getConfig('max_mails');
	if($number_mails_send == 0) {
		$number_mails_send = $addon->getConfig('max_mails');
	}
	$sendresult = $newsletterManager->send($number_mails_send);
	if($sendresult !== TRUE) {
		$messages[] = rex_i18n::msg('multinewsletter_error_send_incorrect_user') .' '. $sendresult;
	}
	if(count($newsletterManager->last_send_users) > 0) {
		$message = rex_i18n::msg('multinewsletter_expl_send_success').'<br /><ul>';
		foreach($newsletterManager->last_send_users as $user) {
			$message .= "<li>";
			if($user->firstname != "" || $user->lastname != "") {
				$message .= $user->firstname ." ". $user->lastname .": ";
			}
			$message .= $user->email ."</li>";
		}
		$message .= "</ul>";
		echo rex_view::success($message);
	}
echo "+++ done";

?>
```
Hast Du noch ein paar Ideen, wie das funktionieren könnte?

**Comment by TobiasKrais** [comment]
Kannst du bitte noch ein paar Daten liefern: Wie viele Empfänger hat der Newsletter? Welcher Wert steht in der `rex_config::get('podcastmanager', 'max_mails')`? Was steht im cronjob log?

**Comment by cukabeka** [comment]
Also aktuell ist nur ein einziger Testuser eingetragen.
Hab den Dump für die max Mails gerade nicht vorliegen, müssten die Standard Einstellungen sein, ist aber NULL.
Cronjob Log sagt nix.

**Comment by TobiasKrais** [comment]
Bist du sicher, dass dein cronjob überhaupt erfolgreich abgeschlossen wird?

**Comment by cukabeka** [comment]
Oh, das war natürlich Unsinn. Ich habe das oben einmal entsprechend korrigiert.

Jetzt bekomme ich die Seetings aus dem Addon:
string(2) "15"

Aber immer noch keine Mail..

**Comment by TobiasKrais** [comment]
Du meinst, dass die Zeile
`var_dump(rex_config::get('multinewsletter', 'max_mails'))`
das Ergebnis string(2) "15" ausgibt? Danach geht wohl was schief, sonst würde ja auch dein Echo am Schluss ausgegeben werden. Dann setze noch ein paar var_dumps zum debuggen in den Code und taste dich an die fehlerhafte Stelle ran.

**Comment by TobiasKrais** [comment]
Hast du Lust ein Modul zu bauen? Ich komme momentan nicht dazu. Hier ein Beispiel: https://github.com/TobiasKrais/d2u_helper/blob/4fb1d4009a28395e204baa3d64094ccdb8580c6f/modules/11/1/output.php

**Comment by cukabeka** [comment]
Im Prinzip gern, allerdings scheitere ich schon daran, den Code so zu stricken, dass überhaupt per cronjob eine Mail versendet wird. 
Was passiert denn, wenn die "prepare" aufgerufen wird? Siehe der Code oben. Leider verstehe ich noch nicht, wie ich $newsletterManager->send benutzen bzw $newsletterManager->last_send_user debuggen kann.

**Comment by TobiasKrais** [comment]
OK, ich verstehe. Ich kenne mich mit Web Requests auch nicht aus und müsste mich komplett rein arbeiten. Mal eine ganz grundsätzliche Frage: was ist denn den Use Case um den Newsletter via IFTTT/Webrequest anzustoßen?

**Comment by TobiasKrais** [comment]
Habe mich entschieden den Punkt nicht umzusetzen. Wenn durch einen Webservice Dienste Angebote werden, dann muss das entsprechend abgesichert sein um kein Einfallstor in Redaxo aufzubauen. Damit kenne ich mich nicht gut genug aus. Da ist mit zu heiß.

**Comment by cukabeka** [comment]
OK, im Prinzip geht es gar nicht um die Webrequests. Das Szenario ist, dass ich einen Newsletter verschicken will, wenn ein Ereignis im Redaxo-System erfolgt.

Das kann zB sein, wenn ein neuer Artikel in einer Kategorie online gestellt wird oder in einer yForm Tabelle ein neuer Eintrag erfolgt. 
Also geht es hier derzeit vor allem um den automatisiert angestoßenen Versand, bei dem ich an eine definierte Gruppe einen definierten Artikel verschicke. Dieser enthält dynamisch generierte Inhalte aus unterschiedlichen Bereichen des Systems, die zu diesem Zeitpunkt verschickt werden sollen. 

Der Webrequest kann dabei auch komplett außen vor gelassen werden. Ich passe den Titel entsprechend an.

**Comment by TobiasKrais** [comment]
Ich verstehe. Das ist jetzt schon möglich. Gegen Bezahlung würde ich da was programmieren.

**Comment by cukabeka** [comment]
Sehr cool! Danke Dir! Bekomme gerade beim Update noch den Error im Backend, wenn ich nach dem Update via Installer/URL-Installer versuche auf die Backend-Seite zuzugreifen:

> Error while executing statement "SELECT archive_id FROM rex_375_sendlist GROUP BY archive_id"! SQLSTATE[42S02]: Base table or view not found: 1146 Table 'rex_375_sendlist' doesn't exist

Evtl ein Update-SQL dazupacken?

**Comment by TobiasKrais** [comment]
Das Update ist schon drin: https://github.com/TobiasKrais/multinewsletter/blob/41cbae88921b7db44fc162277cc54fdda83c5be8/update.php#L94. Bei Update über den Installer läuft es bei mir bei allen Installationen sauber durch. Versuche bitte nochmals über die Addonverwaltung das Addon zu reinstallieren.

**Comment by cukabeka** [comment]
Ah okay, hatte Sorge, dass meine Mail-Adressen-Einträge dabei gelöscht
werden könnten. Bin gerade noch nicht dazu gekommen, das in Ruhe komplett
zu checken.

Danke für deine Antwort!
Liebe Grüße

Tobias Krais <notifications@github.com> schrieb am Do., 13. Sep. 2018,
20:49:

**Comment by TobiasKrais** [comment]
Oder noch besser: setze per  FTP in der package.yml des Addons die Versionssnummer zurück und mach dann das Update nochmals über den Installer. Dann sollten die Tabellen und auch die fehlenden Felder hinzugefügt werden.
