### ISSUE TITLE
Eigene Einstellungen für jede Gruppe

### ISSUE THREAD

**Issue by cukabeka** [TobiasKrais/multinewsletter#25]
Wenn ich komplett unterschiedliche Texte und Absenderadressen haben möchte, ist das mit dem Multinewsletter etwas schwierig zu realisieren.
Idee ist, dass ich bei den Einstellungen zur Gruppe auch einen Artikel, Mailadresse und ggf sogar IMAP Einstellungen hinterlegen kann. Falls dort nichts eingetragen ist, werden als Fallback die normalen Einstellungen und Texte des Addons verwendet.

**Comment by TobiasKrais** [comment]
Gerne als Pull-Request :-)
