### ISSUE TITLE
Multinewsletter Module auf mehreren Webseiten nutzen 

### ISSUE THREAD

**Issue by spiritandsoul** [TobiasKrais/multinewsletter#26]
Hey Tobi,

Ich habe da mal an Dich, bzw. in die Runde eine Frage. Ich betreibe drei Redaxo Seiten und hätte normalerweise 3 Multinewsletter installiert. Ich würde gern den Newsletter über eine Instanz ausgeben und steuern, man sollte sich über die anderen beiden Seiten auch eintragen können. Meine Frage hat vielleicht jemand sowas schon umgesetzt? Also Module die eine andere Datenbank ansteuern oder via Iframe ein Formular ausgeben wie bei Mailchimp um es als Modul auszugeben?

Danke im Vorraus und schönen Sonntag!

LG Christian :-)

**Comment by TobiasKrais** [comment]
Hast du drei separate Redaxo Installationen oder eine Installation mit drei Domains und YRewrite? Das wäre nämlich die einfachste Möglichkeit.

Eine andere Möglichkeit wäre über Redaxo die 2. Datenbank zu nutzen. Aber da habe ich wenig Erfahrung drin.

**Comment by spiritandsoul** [comment]
Danke Dir.

An YRewrite dachte ich auch schon, wenn ich nicht Newsmanager Addons am laufen hätte. Dann ist die einfachste Sache mir einen guten Grund einfallen zu lassen. warum sie sich auf einer anderen Seite eintragen sollen.

Zum nem zweiten Modul mit anderer Datenbank frage ich mal Rudi. will seine Meinung dazu mal hören.
