### ISSUE TITLE
Anhang wird nicht mitverschickt

### ISSUE THREAD

**Issue by rotzek** [TobiasKrais/multinewsletter#29]
Multinewsletter ist in der aktuellen Version installiert und eingerichtet, alles funktioniert wunderbar - bis auf den Versand einer oder mehrer Anlage(n). Diese lassen sich zwar auswählen, werden aber nicht verschickt.

**Comment by TobiasKrais** [comment]
@rotzek: Kannst du bitte die /lib/newsletter.php Datei aus dem Commit oben verwenden und nochmals testen?
