### ISSUE TITLE
Whoops-Error beim Deaktivieren des AddOns

### ISSUE THREAD

**Issue by dpf-dd** [TobiasKrais/multinewsletter#30]
Wenn ich den aktuellen MultiNewsletter 3.2.1. (Redaxo 5.6.4) deaktivieren möchte, dann bekomme ich einen Whoops: "Class 'multinewsletter_cronjob_sender' not found"
Angezeigt in der uninstall.php (Zeile 8-10):
```// Remove CronJob
if(multinewsletter_cronjob_sender::isInstalled()) {
    multinewsletter_cronjob_sender::delete();
}

**Comment by TobiasKrais** [comment]
Danke für die Fehlermeldung. Den Fehler kann ich auf allen meinen Installationen nicht nachvollziehen. Hast du per Installer aktualisiert oder von Hand? Was passiert, wenn du den Redaxo Cache leerst?

**Comment by gharlan** [comment]
> beim Deaktivieren des AddOns

Du meinst beim Deinstallieren, oder?
War das Addon vorher schon deaktiviert?

**Comment by dpf-dd** [comment]
OK, es ist bei mir unter folgenden Umständen reproduzierbar:
1) frisch installiertes Redaxo 5.6.4 (Cronjob-Addon NICHT installiert)
2) d2u_helper 1.5.0 und MultiNewsletter 3.2.1 aus dem Installer heraus installiert
3) MultiNewsletter jetzt DEAKTIVIEREN (funktioniert)
4) MultiNewsletter jetzt DEINSTALLIEREN (=> WHOOPS-Fehler erscheint...)

Wichtig: Wenn man Punkt 3 auslässt und das aktive AddOn DIREKT deinstalliert - dann geht das.
Kann das jemand ebenfalls reproduzieren?

**Comment by TobiasKrais** [comment]
@gharlan: Generelle Frage: wenn ein Addon deaktiviert ist, werden offensichtlich die Klassen nicht mehr über den Autoloader geladen. Damit kann ich in der uninstall.php nicht mehr auf die Klassen zugreifen, die für die Deinstallation nötigen wären. Ist das von Redaxo so erwünscht?

**Comment by TobiasKrais** [comment]
Wird in der nächsten Version behoben sein.
