### ISSUE TITLE
Bug: Wenn title leer

### ISSUE THREAD

**Issue by thielpeter** [TobiasKrais/multinewsletter#31]
https://github.com/TobiasKrais/multinewsletter/blob/835605cc6b7fccad58362186ac470ec57a75e252/lib/user.php#L285

Es kommt zu einem Fehler sobald der Titel leer ist. Vorschlag:
`."title = '". $this->title ."', "`

**Comment by TobiasKrais** [comment]
Du hast recht. Danke für den Hinweis. Das title Feld ist ein TINYINT Feld. Deshalb funktioniert dein Vorschlag nicht. Kannst du meinen Bugfix testen?

**Comment by thielpeter** [comment]
Mein Bugfix hat bei mir funktioniert :) Es geht ja nur darum, dass das SQL valide ist was mit 'tinyint' ja auch stimmen würde, oder sehe ich das falsch?

**Comment by TobiasKrais** [comment]
Die DB wird meckern wird, wenn der Wert title = '1' eingegeben wird, also wenn das Fehd einen Wert beinhaltet. Mit meinem Bugfix hat man beide Möglichkeiten drin und beachtet auch den Typ der Variable (das ist sauber).
