### ISSUE TITLE
Anmelde-Infomail customisieren

### ISSUE THREAD

**Issue by cukabeka** [TobiasKrais/multinewsletter#33]
Habe hier die Stelle gefunden: 
https://github.com/TobiasKrais/multinewsletter/blob/463be4b9f0143c0dee32c020a0630730bb178287/lib/user.php#L384
Ich möchte gerne Betreff und Mail-Inhalt beeinflussen können, ggf per YFORM Mailtemplate oder über das Sprach-Setup und Platzhaltern, zB +++MAIL+++ oder +++GROUPNAME+++. Mein Ziel ist es, dass ich zusätzlich auch den Namen der Gruppe in der Bestätigung habe, zB im Betreff.

**Comment by TobiasKrais** [comment]
Habe ich richtig verstanden, dass es dir nur um den Namen der Gruppe geht? Der ist schwierig zu identifizieren. Es gibt zwei Beziehungen zur Gruppe:
a) Ein Nutzer kann mehreren Gruppen angehören. Ist ist durch diese 1:n Beziehung nicht möglich die Gruppen mit Sicherheit herauszufinden.
b) Beim Versand können mehrere Gruppen ausgewählt werden. Hier haben wir, wenn es unglücklich läuft eine n:n Beziehung.

Ich vermute, dass du immer nur an eine Gruppe Mails sendest. Da wäre das kein Problem. MultiNewsletter soll aber offen für andere Möglichkeiten bleiben. Hilft dir dieser Hintergrund?
