### ISSUE TITLE
Multinewsletter verschickt immer nur Startseite?

### ISSUE THREAD

**Issue by simonsinus** [TobiasKrais/multinewsletter#35]
Obwohl ich beim Testmailversand den gewollten Artikel ausgewählt habe,
verschickt das Addon nur die Seiten-Startseite mit dem Newsletter Template.

**Comment by simonsinus** [comment]
OK, das Problem ist gelöst. Man darf den Artikel nicht über Rex XCore einbinden sondern über die Redaxo API.

`<?php echo rex_article_content::getArticle(); ?>`

**Comment by TobiasKrais** [comment]
Spannend. Gut, dass du es lösen konntest!
