### ISSUE TITLE
Kombination mit bloecks

### ISSUE THREAD

**Issue by ritzfritz** [TobiasKrais/multinewsletter#39]
Per bloecks ausgeblendete Slices werden trotz Ausblenden per Mail versandt.

**Comment by TobiasKrais** [comment]
Super, dass du deinen ersten Issue gemacht hast. Kann mir jemand sagen, wie ich den Status der Blöcke berücksichtige? Weiß jemand wie diese Zeile lauten sollte, damit nur online Blöcke berücksichtigt werden? https://github.com/TobiasKrais/multinewsletter/blob/20f9e7bdc813e14f50fe0c8cb31d3674a3ff0d70/lib/newsletter.php#L279

**Comment by ritzfritz** [comment]
die rex_article_slice wird um die Spalte a356_is_online erweitert in der dann 0 oder 1 steht. Das sollte da irgendwie rein...

**Comment by TobiasKrais** [comment]
Ich nutze eine Standard Redaxo Funktion, da habe ich nicht viele Einstellungsmöglichkeiten...

**Comment by alexplusde** [comment]
In R5 heißt das Feld `status`, nicht a356_is_online

Wie renderst du denn den Artikelinhalt?

**Comment by ritzfritz** [comment]
@alexplusde Du hast Recht, resultierte aus einer REX4->REX5 Transformation....

**Comment by TobiasKrais** [comment]
> Wie renderst du denn den Artikelinhalt?

Gar nicht. Der kommt schon gerendert aus `$article_content->getArticleTemplate();` raus. Das ist der fertige Inhalt.

**Comment by alexplusde** [comment]
Konzeptionell läuft da was schief, weil du dich im Backend befindest und nicht im Frontend. Im Backend wird der Inhalt jedes ausgeblendeten slices gerendert. Du müsstest dir den Inhalt aus dem Frontend holen oder temporär die Variable ändern, die festlegt, ob du im FE oder BE bist.

Evtl reicht es, davor und danach $REX['REDAXO'] = true; auf false und wieder auf true zu stellen, bevor du den Artikel aufrufst.

**Comment by TobiasKrais** [comment]
> Evtl reicht es, davor und danach $REX['REDAXO'] = true; auf false und wieder auf true zu stellen, bevor und nachdem du den Artikel aufrufst.

Sprechen wir jetzt von R4 oder R5? Ich dachte der Issue ist in R5. Oder liege ich da falsch?

**Comment by alexplusde** [comment]
Schau Mal in die index.php von Frontend und Backend, dann weißt du, warum ich das vorschlage :)

**Comment by TobiasKrais** [comment]
So, jetzt hatte ich endlich Zeit, zu testen. `$REX['REDAXO'] = true;` hilft leider nicht :-(

**Comment by alexplusde** [comment]
Dann weiß ich leider auch nicht weiter. Ich erinnere mich noch - es gab mal ein Addon, das einen Frontend-Aufruf im Backend simuliert hat - aber keine Idee mehr, welches das war. :(

Ansonsten evtl. mal bei search_it abkupfern, wie die Seite einfach aus dem Frontend per rex_socket abgerufen wird.

**Comment by TobiasKrais** [comment]
Du bist der Knaller! Das ist mit search_it, ist die Idee! So mach ich das. Und als Fallback wird die alte Funktion verwendet.

**Comment by TobiasKrais** [comment]
@ritzfritz: bei mir funktioniert der Fix im Commit. Geht er bei dir auch? Kannst du das bitte mal testen?

**Comment by ritzfritz** [comment]
Ähm, was meinst Du? Wo ist der Fix? Was ist Commit?

**Comment by TobiasKrais** [comment]
Kein Problem. Schau mal neben dem roten Kreis mit Verbotsschild zwischen meinen beiden Posts steht die Zahl 1529309 mit Link dahinter. Wenn du darauf klickst, siehst du welche Änderung ich an der Programmierung gemacht habe um das Problem zu lösen. Die Änderung kannst du in deinem Code übernehmen. Oder du lädst dir diese Datei herunter: https://github.com/TobiasKrais/multinewsletter/blob/master/lib/newsletter.php und lädst sie auf deine Webseite hoch.

**Comment by ritzfritz** [comment]
Mit der modifizierten newsletter.php werden die +++VARIABLEN+++ nicht mehr ersetzt. Mist.

**Comment by TobiasKrais** [comment]
Bei mir werden sie korrekt ersetzt. Zumindest in der Testmail. Die Änderung hat gar nichts mit dem Versand und damit dem Ersetzen der Variablen zu tun. Da sollte alles unverändert bleiben.

Kannst du ausschließen, dass bei den Variablen ein Fehler drin steckt?
Welche Redaxo und MultiNewsletter Version nutzt du?

**Comment by ritzfritz** [comment]
Definitiv werden mit der neuen newsletter.php die Variablen nicht ersetzt. bleiben komplett leer. MNL 3.2.5, REX 5.7.1, PHP 7.3.5.
Weder bei der Testmail, noch in der endlichen Version.
Die Variablen funktionieren ja in der originalen Version. Danke Dir schon mal!

**Comment by TobiasKrais** [comment]
Hi @ritzfritz: nachdem ich alle Ersetzungsvariablen getestet habe, weiß ich was du meinst. Kannst du bitte mal die boot.php und lib/newsletter.php mit der aktuellen (siehe Commit) austauschen und nochmals testen? Der Fehler, den du entdeckt hast, hängt nicht mit diesem Issue zusammen und steckt schon länger im MultiNewsletter...

**Comment by ritzfritz** [comment]
Mach ich morgen...

**Comment by TobiasKrais** [comment]
Da ich nach den Tests nichts mehr höre, gehe ich davon aus, dass alles funktioniert  und schließe den Issue.
