### ISSUE TITLE
Fehler beim mehrsprachigen Versand 

### ISSUE THREAD

**Issue by Poper123** [TobiasKrais/multinewsletter#41]
Hallo,

ich habe einen Newsletter in deutsch und englisch angelegt. Nur wenn ich den englischen "offline" schalte, funktioniert der Versand des Newsletters. 

Die Fehlermeldung:
Error while executing statement "INSERT INTO rex_375_archive SET article_id = 124, clang_id = 2, subject = 'xxxx', htmlbody = 'xxxx', attachments = '', recipients = '', recipients_failure = '', group_ids = '|1|2|3|4|', sender_email = 'x@x.de', sender_name = 'xxxx', setupdate = '2019-08-12 13:42:21', sentdate = '', sentby = 'admin' "! SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '2019-08-12 13:42:21' for key 'setupdate'

Grüße Axel

**Comment by TobiasKrais** [comment]
Danke für die Fehlermeldung. Ich kümmere mich darum. Bis dahin bitte ich dich als Workaround den UNIQUE Key auf der Spalte setupdate aus der Datenbanktabelle rex_375_archive zu entfernen.

**Comment by TobiasKrais** [comment]
Falls du den UNIQUE Key noch nicht gelöscht hast, kannst du mir bitte schreiben, aus was der UNIQUE Key besteht? Er sollte aus setupdate und clang_id bestehen. Vermutlich besteht er bei dir nur aus setupdate. Falls das so ist, kannst du mir sagen, ob du die MutliNewsletter Daten aus Redaxo 4 importiert hast, oder ob ob du das Addon neu installiert hattest.

Ich kann den Fehler bei mir leider nicht nachvollziehen.

**Comment by Poper123** [comment]
Sorry, kam erst jetzt dazu nachzuschauen. Wie du vermutet hast, es steht nur setupdate drin (habe clang_id hinzugefügt). Und ja, ich habe es aus Redaxo4. Danke.

**Comment by TobiasKrais** [comment]
Seltsam. Eigentlich hätte das beim Import korrigiert werden sollen:
https://github.com/TobiasKrais/multinewsletter/blob/53d432f806743f3167ff1677aa5e0ad2cf124370/install.php#L23-L24

Es scheint ein Einzelfall zu sein. Daher schließe ich den Issue. Gut, dass es bei dir jetzt korrekt funktioniert.
