### ISSUE TITLE
Spam-Gefahr durch Seiten-Reload bei der Newsletter-Anmeldung

### ISSUE THREAD

**Issue by frood** [TobiasKrais/multinewsletter#42]
Das Modul für die Newsletteranmeldung sendet erneut bei Seitenreload > Spamgefahr!
Einmal Daten eingeben, abschicken, 4xSeite neu laden => macht fünf mails!
Dies kann über eine Session-Var beim Versand der Bestätigungsmail leicht unterbunden werden.
#43

**Comment by TobiasKrais** [comment]
Hierfür bitte die YForm Beispielmodule nehmen. Dort ist auch der von YForm mitgelieferte XSS Schutz drin. Zum PR siehe den Code Comment.
