### ISSUE TITLE
yrewrite Problem bei der Testmail im Backend

### ISSUE THREAD

**Issue by thorol** [TobiasKrais/multinewsletter#44]
yrewrite ist richtig eingerichtet. Der Aufruf des Newsletter-Artikel funktioniert im Frontend ohne Probleme.

**Error:** Call to a member function getId() on null
**File:** redaxo/src/addons/yrewrite/lib/yrewrite/yrewrite.php
**Line:** 132

<details>
<summary>Stacktrace</summary>

| Function                                     | File                                                   | Line     |
| -------------------------------------------- | ------------------------------------------------------ | -------- |
| rex_yrewrite::getCurrentDomain               | redaxo/src/addons/multinewsletter/lib/newsletter.php   | 188      |
| MultinewsletterNewsletter::replaceURLs       | redaxo/src/addons/multinewsletter/lib/newsletter.php   | 393      |
| MultinewsletterNewsletter->send              | redaxo/src/addons/multinewsletter/lib/newsletter.php   | 432      |
| MultinewsletterNewsletter->sendTestmail      | redaxo/src/addons/multinewsletter/pages/newsletter.php | 240      |
| include                                      | redaxo/src/core/lib/packages/package.php               | 245      |
| rex_package->includeFile                     | redaxo/src/core/lib/be/controller.php                  | 471      |
| rex_be_controller::includePath               | redaxo/src/core/lib/be/controller.php                  | 428      |
| rex_be_controller::includeCurrentPageSubPath | redaxo/src/addons/multinewsletter/pages/index.php      | 22       |
| include                                      | redaxo/src/core/lib/packages/package.php               | 245      |
| rex_package->includeFile                     | redaxo/src/core/lib/be/controller.php                  | 471      |
| rex_be_controller::includePath               | redaxo/src/core/lib/be/controller.php                  | 413      |
| rex_be_controller::includeCurrentPage        | redaxo/src/core/backend.php                            | 226      |
| require                                      | redaxo/src/core/boot.php                               | 137      |
| require                                      | redaxo/index.php                                       | 9        |

</details>
<details>
<summary>System report (REDAXO 5.10.1, PHP 7.3.6)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.10.1     |

| PHP           |                                |
| ------------: | :----------------------------- |
|       Version | 7.3.6                          |
|       OPcache | no                             |
|        Xdebug | no                             |
|       Warning | Das Setup wird ohne HTTPS/Verschlüsselung durchgeführt. Es wird empfohlen jegliche Frontend und Backend aufrufe nur mittels HTTPS durchzuführen, um die Privatsphäre und den Datenschutz zu gewährleisten.<br/>In den PHP-Einstellungen ist &quot;session.auto_start&quot; aktiviert. Es wird empfohlen, dies zu deaktiveren, um Probleme zu vermeiden. |

| Database      |              |
| ------------: | :----------- |
|       Version | MySQL 5.6.19 |
| Character set | utf8         |

| Server        |               |
| ------------: | :------------ |
|            OS | Linux         |
|          SAPI | cgi-fcgi      |
|     Webserver | Apache/2.4.41 |

| Request       |                      |
| ------------: | :------------------- |
|       Browser | Chrome/83.0.4103.106 |
|      Protocol | HTTP/1.1             |
|         HTTPS | no                   |

| Packages                               |            |
| -------------------------------------: | :--------- |
|                                 backup | 2.6.0      |
|                               be_style | 2.10.1     |
|                        be_style/arttec | 0.0.0      |
|                        be_style/redaxo | 2.10.1     |
|                                bloecks | 3.0.0      |
|                       bloecks/cutncopy | 3.0.0      |
|                      bloecks/dragndrop | 3.0.0      |
|                         bloecks/status | 3.0.0      |
|                                cronjob | 2.7.0      |
|                 cronjob/article_status | 2.0.0      |
|                cronjob/optimize_tables | 2.6.0      |
|                             d2u_helper | 1.6.1      |
|                              developer | 3.9.0      |
|                              event_cal | 1.1.3      |
|                             focuspoint | 2.2.2      |
|                                install | 2.7.1      |
|                            maintenance | 2.3.0      |
|                                 mblock | 3.1.0      |
|                          media_manager | 2.9.1      |
|                     media_manager_plus | 2.0.0      |
|                           media_srcset | 2.0        |
|                              mediapool | 2.8.1      |
|                               metainfo | 2.7.1      |
|                                  mform | 5.3.1      |
|                             mform/docs | 1.0        |
|                        multinewsletter | 3.2.6      |
|                            multiupload | 2.1.3      |
|             multiupload/imageoptimizer | 1.0.1      |
|       multiupload/upload_precompressor | 1.0        |
|                              phpmailer | 2.8.2      |
|                                project | dev        |
|                       quick_navigation | 3.7.2      |
|                              redactor2 | 4.0.3      |
|                              search_it | 6.7.2      |
|                 search_it/autocomplete | 6.7.2      |
|                search_it/documentation | 6.7.2      |
|                    search_it/plaintext | 6.7.2      |
|                        search_it/stats | 6.7.2      |
|                                  sprog | 1.2.0      |
|                              structure | 2.10.1     |
|                      structure/content | 2.10.1     |
|                      structure/history | 2.10.0     |
|                      structure/version | 2.10.0     |
|                                  users | 2.6.2      |
|                                  yfeed | 1.3.0      |
|                                  yform | 3.4        |
|                             yform/docs | 3.3.1      |
|                            yform/email | 3.4        |
|                          yform/manager | 3.4        |
|                               yrewrite | 2.6        |

</details>
**Error:** Call to a member function getId() on null
**File:** redaxo/src/addons/yrewrite/lib/yrewrite/yrewrite.php
**Line:** 132

<details>
<summary>Stacktrace</summary>

| Function                                     | File                                                   | Line     |
| -------------------------------------------- | ------------------------------------------------------ | -------- |
| rex_yrewrite::getCurrentDomain               | redaxo/src/addons/multinewsletter/lib/newsletter.php   | 188      |
| MultinewsletterNewsletter::replaceURLs       | redaxo/src/addons/multinewsletter/lib/newsletter.php   | 393      |
| MultinewsletterNewsletter->send              | redaxo/src/addons/multinewsletter/lib/newsletter.php   | 432      |
| MultinewsletterNewsletter->sendTestmail      | redaxo/src/addons/multinewsletter/pages/newsletter.php | 240      |
| include                                      | redaxo/src/core/lib/packages/package.php               | 245      |
| rex_package->includeFile                     | redaxo/src/core/lib/be/controller.php                  | 471      |
| rex_be_controller::includePath               | redaxo/src/core/lib/be/controller.php                  | 428      |
| rex_be_controller::includeCurrentPageSubPath | redaxo/src/addons/multinewsletter/pages/index.php      | 22       |
| include                                      | redaxo/src/core/lib/packages/package.php               | 245      |
| rex_package->includeFile                     | redaxo/src/core/lib/be/controller.php                  | 471      |
| rex_be_controller::includePath               | redaxo/src/core/lib/be/controller.php                  | 413      |
| rex_be_controller::includeCurrentPage        | redaxo/src/core/backend.php                            | 226      |
| require                                      | redaxo/src/core/boot.php                               | 137      |
| require                                      | redaxo/index.php                                       | 9        |

</details>
<details>
<summary>System report (REDAXO 5.10.1, PHP 7.3.6)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.10.1     |

| PHP           |                                |
| ------------: | :----------------------------- |
|       Version | 7.3.6                          |
|       OPcache | no                             |
|        Xdebug | no                             |
|       Warning | Das Setup wird ohne HTTPS/Verschlüsselung durchgeführt. Es wird empfohlen jegliche Frontend und Backend aufrufe nur mittels HTTPS durchzuführen, um die Privatsphäre und den Datenschutz zu gewährleisten.<br/>In den PHP-Einstellungen ist &quot;session.auto_start&quot; aktiviert. Es wird empfohlen, dies zu deaktiveren, um Probleme zu vermeiden. |

| Database      |              |
| ------------: | :----------- |
|       Version | MySQL 5.6.19 |
| Character set | utf8         |

| Server        |               |
| ------------: | :------------ |
|            OS | Linux         |
|          SAPI | cgi-fcgi      |
|     Webserver | Apache/2.4.41 |

| Request       |                      |
| ------------: | :------------------- |
|       Browser | Chrome/83.0.4103.106 |
|      Protocol | HTTP/1.1             |
|         HTTPS | no                   |

| Packages                               |            |
| -------------------------------------: | :--------- |
|                     arttec_agenturtool | 0.7.3      |
|                          arttec_helper | 2.3.2      |
|                         arttec_smodule | 3.3.0      |
| arttec_smodule/arttec_smodule_standard | 1.0.0      |
|                                 backup | 2.6.0      |
|                               be_style | 2.10.1     |
|                        be_style/arttec | 0.0.0      |
|                        be_style/redaxo | 2.10.1     |
|                                bloecks | 3.0.0      |
|                       bloecks/cutncopy | 3.0.0      |
|                      bloecks/dragndrop | 3.0.0      |
|                         bloecks/status | 3.0.0      |
|                                cronjob | 2.7.0      |
|                 cronjob/article_status | 2.0.0      |
|                cronjob/optimize_tables | 2.6.0      |
|                             d2u_helper | 1.6.1      |
|                              developer | 3.9.0      |
|                              event_cal | 1.1.3      |
|                             focuspoint | 2.2.2      |
|                                install | 2.7.1      |
|                            maintenance | 2.3.0      |
|                                 mblock | 3.1.0      |
|                          media_manager | 2.9.1      |
|                     media_manager_plus | 2.0.0      |
|                           media_srcset | 2.0        |
|                              mediapool | 2.8.1      |
|                               metainfo | 2.7.1      |
|                                  mform | 5.3.1      |
|                             mform/docs | 1.0        |
|                        multinewsletter | 3.2.6      |
|                            multiupload | 2.1.3      |
|             multiupload/imageoptimizer | 1.0.1      |
|       multiupload/upload_precompressor | 1.0        |
|                              phpmailer | 2.8.2      |
|                                project | dev        |
|                       quick_navigation | 3.7.2      |
|                              redactor2 | 4.0.3      |
|                              search_it | 6.7.2      |
|                 search_it/autocomplete | 6.7.2      |
|                search_it/documentation | 6.7.2      |
|                    search_it/plaintext | 6.7.2      |
|                        search_it/stats | 6.7.2      |
|                                   shop | 1.1.6      |
|               shop/paymentBanktransfer | 0.0.1      |
|                        shop/paymentBar | 0.0.1      |
|                     shop/paymentPaypal | 0.0.1      |
|                      shop/shipDPDCloud | 0.0.1      |
|                                  sprog | 1.2.0      |
|                              structure | 2.10.1     |
|                      structure/content | 2.10.1     |
|                      structure/history | 2.10.0     |
|                      structure/version | 2.10.0     |
|                                  users | 2.6.2      |
|                                  yfeed | 1.3.0      |
|                                  yform | 3.4        |
|                             yform/docs | 3.3.1      |
|                            yform/email | 3.4        |
|                          yform/manager | 3.4        |
|                               yrewrite | 2.6        |

</details>

**Comment by TobiasKrais** [comment]
Hi Thomas, leider kann ich den Fehler nicht nachvollziehen. Ist das schon bei der Testmail so dass der Fehler kommt?

**Comment by thorol** [comment]
Ja, bereits bei der Testmail. Er hat ja die Probleme mit rex_yrewrite::getCurrentDomain? Muss der rex_article vorher übergeben worden sein, so dass auch yrewrite sagen kann, dass ist ID x, denn woher sollte es sonst yrewrite im Backend wissen? Was nimmt yrewrite ansonsten?

Da es auch in einer anderen Installation ging, habe ich gerade mal geschaut, was die Unterschiede sind. Im System-Addon war der Startartikel, wie auch Fehlerartikel ausgefüllt. Das habe ich nun auch für diese Installation getan, jetzt geht alles. 
Ich bin mir aber dann nicht sicher, ob der Newsletter immer mit der richtigen Domain versendet wird, denn eigentlich sollten die Einstellungen unter system egal sein...

**Comment by TobiasKrais** [comment]
OK. Jetzt ist mir der Fehler klar. In den MultiNewsletter Einstellungen hast du vermutlich unter "Methode zum Auslesen des Artikels" den Wert "Redaxo intern" ausgewählt. Da kommt das zum tragen. Muss ich mir in der Tat mal anschauen. Da steckt ein potentieller Fehler drin.

**Comment by TobiasKrais** [comment]
Thomas, könntest du bitte den Fix von gerade eben testen, ob der Fehler noch kommt?

**Comment by thorol** [comment]
Ja, das mach ich und gebe Dir ne Rückmeldung.
