### ISSUE TITLE
Undefined index: attachments

### ISSUE THREAD

**Issue by danspringer** [TobiasKrais/multinewsletter#45]
Wenn ich die AddOn-Seite multinewsletter/newsletter aufrufe bekomme ich folgenden Log-Eintrag in Redaxo:

`Notice | Undefined index: attachments | redaxo/src/addons/multinewsletter/pages/newsletter.php | 191`

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.11.0     |

| PHP           |            |
| ------------: | :--------- |
|       Version | 7.2.33     |
|       OPcache | yes        |

| Packages                   |            |
| -------------------------: | :--------- |
multinewsletter | 3.2.7      |

**Comment by TobiasKrais** [comment]
@danspringer: danke, dass du das gemeldet hast! Kannst du evtl. testen, ob der Fehler damit behoben ist?

**Comment by danspringer** [comment]
Bekomme jetzt auf jeden Fall keine Notice mehr.

**Comment by TobiasKrais** [comment]
Super. Danke fürs Testen!
