### ISSUE TITLE
Bei Update: Exception: key_exists(): Argument #2 ($array) must be of type array, null given

### ISSUE THREAD

**Issue by thorol** [TobiasKrais/multinewsletter#49]
Bei einem Update von Version 3.2.8 auf 3.3.1 unter PHP 8.1 kommt folgender Fehler:

**Request-Uri:** /redaxo/index.php?page=install/packages/update&addonkey=multinewsletter&file=4560&rex-api-call=install_package_update&_csrf_token=-cFkWnq7ha_QOmdQ172FIptqqBytNnzKzRkz_-Ryk3o
**Request-Method:** GET

**TypeError:** key_exists(): Argument #2 ($array) must be of type array, null given
**File:** redaxo/src/addons/d2u_helper/lib/d2u_module_manager.php
**Line:** 550

<details>
<summary>Stacktrace</summary>

| Function | File | Line |
| --------------------------------------- | ---------------------------------------------------------- | -------- |
| key_exists | redaxo/src/addons/d2u_helper/lib/d2u_module_manager.php | 550 |
| D2UModule->initRedaxoContext | redaxo/src/addons/d2u_helper/lib/d2u_module_manager.php | 49 |
| D2UModuleManager->__construct | redaxo/src/addons/.new.multinewsletter/install.php | 101 |
| require | redaxo/src/core/lib/packages/package.php | 284 |
| rex_package->includeFile | redaxo/src/addons/.new.multinewsletter/update.php | 20 |
| require | redaxo/src/core/lib/packages/package.php | 280 |
| rex_package->includeFile | redaxo/src/addons/install/lib/package/package_update.php | 61 |
| rex_install_package_update->doAction | redaxo/src/addons/install/lib/package/package_download.php | 44 |
| rex_install_package_download->run | redaxo/src/addons/install/lib/api/api_package_update.php | 21 |
| rex_api_install_package_update->execute | redaxo/src/core/lib/api_function.php | 182 |
| rex_api_function::handleCall | redaxo/src/core/backend.php | 235 |
| require | redaxo/src/core/boot.php | 143 |
| require | redaxo/index.php | 9 |

</details>
<details>
<summary>System report (REDAXO 5.14.2, PHP 8.1.9, MariaDB 10.9.3)</summary>

| REDAXO | |
| ------------: | :--------- |
| Version | 5.14.2 |

| PHP | |
| ------------: | :----------------------------- |
| Version | 8.1.9 |
| OPcache | no |
| Xdebug | no |
| Warning | Das Setup wird unverschlüsselt durchgeführt. Frontend und Backend sollten grundsätzlich durch HTTPS verschlüsselt aufgerufen werden, um die Privatsphäre zu schützen und den Datenschutz zu gewährleisten. |

| Database | |
| ------------: | :------------- |
| Version | MariaDB 10.9.3 |
| Character set | utf8mb4 |

| Server | |
| ------------: | :------------- |
| OS | Linux |
| SAPI | apache2handler |
| Webserver | Apache/2.4.54 |

| Request | |
| ------------: | :--------------- |
| Browser | Chrome/108.0.0.0 |
| Protocol | HTTP/1.1 |
| HTTPS | no |

| Packages | |
| --------------------------------------: | :----------- |
| backup | 2.8.2 |
| be_style | 3.1.1 |
| be_style/customizer | 3.1.0 |
| be_style/redaxo | 3.1.1 |
| be_tools | 1.7.7 |
| bloecks | 3.1.1 |
| bloecks/cutncopy | 3.1.1 |
| bloecks/dragndrop | 3.1.1 |
| bloecks/status | 3.1.1 |
| consent_manager | 3.0.8 |
| cronjob | 2.9.0 |
| cronjob/article_status | 2.8.1 |
| cronjob/optimize_tables | 2.8.1 |
| d2u_helper | 1.9.3 |
| developer | 3.9.2 |
| focuspoint | 4.0.3 |
| install | 2.10.0 |
| maintenance | 2.8.5 |
| mblock | 3.4.7 |
| media_manager | 2.13.2 |
| media_manager_autorewrite | 2.0.1 |
| media_manager_plus | 2.2.1 |
| media_srcset | 2.1.0 |
| mediapool | 2.12.0 |
| metainfo | 2.9.0 |
| mform | 7.2.7 |
| mform/docs | 1.1 |
| multinewsletter | 3.2.8 |
| multiupload | 2.1.3 |
| multiupload/imageoptimizer | 1.0.1 |
| multiupload/upload_precompressor | 1.0 |
| osmproxy | 1.6.0 |
| phpmailer | 2.11.2 |
| project | dev |
| quick_navigation | 6.0.1 |
| redactor2 | 4.2.1 |
| search_it | 6.9.5 |
| search_it/autocomplete | 6.9.5 |
| search_it/documentation | 6.9.5 |
| search_it/plaintext | 6.9.5 |
| search_it/stats | 6.9.5 |
| seocheckup | 1.6.5 |
| sprog | 1.5.1 |
| structure | 2.14.2 |
| structure/content | 2.14.2 |
| structure/history | 2.14.2 |
| structure_tweaks | 1.4.0 |
| url | 2.0.2 |
| users | 2.9.1 |
| ydeploy | 1.1.1 |
| yfeed | 1.3.0 |
| yform | 4.0.4 |
| yform/email | 4.0.4 |
| yform/manager | 4.0.4 |
| yform_geo_osm | 1.2.6 |
| yform_spam_protection | 1.2.3 |
| yrewrite | 2.9.1 |
| yrewrite_domain_settings | 2.1.2 |

</details>

**Comment by TobiasKrais** [comment]
Das ist ein Fehler im d2u_helper Addon. Der müsste in der aktuellen Git Version behoben sein. Kannst du versuchen die Git Version vom D2U Helper zu ziehen (https://github.com/TobiasKrais/d2u_helper) und dann das Update nochmals testen?

**Comment by thorol** [comment]
Alles klar, werde ich testen.

Von: Tobias Krais ***@***.***>
Gesendet: Donnerstag, 5. Januar 2023 20:17
An: TobiasKrais/multinewsletter ***@***.***>
Cc: Thomas Rolinger ***@***.***>; Author ***@***.***>
Betreff: Re: [TobiasKrais/multinewsletter] Bei Update: Exception: key_exists(): Argument #2 ($array) must be of type array, null given (Issue #49)


Das ist ein Fehler im d2u_helper Addon. Der müsste in der aktuellen Git Version behoben sein. Kannst du versuchen die Git Version vom D2U Helper zu ziehen (https://github.com/TobiasKrais/d2u_helper) und dann das Update nochmals testen?

**Comment by thorol** [comment]
@TobiasKrais: Mit der Github-Version gibt es keine Probleme. Evtl. Versions-Abhängigkeiten in ynewsletter einbauen?

**Comment by TobiasKrais** [comment]
Vielen Dank für deinen Test. Ich überarbeite gerade den D2U Helper mit rexstan. Wenn ich fertig bin mache ich eine neue Version und dann ist der Multinewsletter dran. Soll ich deiner Meinung nach schon vorher ein Release raus lassen oder reicht es, wenn wir 2-3 Wochen warten?

**Comment by thorol** [comment]
Wenn die älteren Versionen des multinewsletter bereits heute auf PHP 8.1 gut laufen, denke ich, dass es kein Problem ist 2-3 Wochen zu warten. Es könnte natürlich sein, dass andere in die gleichen Fehler laufen.

**Comment by TobiasKrais** [comment]
PHP 8.1 ist kein Problem. Bisher hatte niemand ein ähnliches Problem. Ich warte mal ab, ob jemand anders das auch erlebt. Falls ja, schiebe ich kurzfristig ein Update raus. Danke dir!
