### ISSUE TITLE
Funktionswunsch: Anhang auch in Testmail versenden

### ISSUE THREAD

**Issue by dpf-dd** [TobiasKrais/multinewsletter#50]
Hallo Tobias,

wie du weißt nutze ich dein AddOn sehr gerne sobald ich die Aufgabe "Newsletter" habe. Eine Sache fällt mir regelmäßig auf - und jetzt äußere ich den Wunsch einfach mal...

Wäre es irgendwie machbar, dass man einen Newsletter-Anhang (zB. PDF-Datei) bereits vor dem Versenden des Testnewsletters anhängt? 
<img width="687" alt="Bildschirmfoto 2023-01-20 um 13 45 41" src="https://user-images.githubusercontent.com/10958385/213698124-73fbfa52-36b2-466d-8cb9-bdf4052ce7b0.png">

Ich habe oft den Fall, dass der NL an sich vom Text gleich bleibt, aber jede Woche ein für die Folgewoche aktuelles PDF angehängt wird. Die aktuelle "Testmail" ist für mich in diesem Szenario sinnlos... :)

Also nicht falsch verstehen - das soll nur ein wertungsfreies Feedback sein. Ich finde das AddOn trotzdem toll <3

**Comment by TobiasKrais** [comment]
Hi Stefan, dein Wunsch macht absolut Sinn. Im Moment komme ich nicht dazu. Hast du zufällig einen PR dafür?

**Comment by TobiasKrais** [comment]
Kannst du bitte bei Gelegenheit die aktuelle Git Version testen, ob dein Wunsch korrekt funktioniert?
