### ISSUE TITLE
Die Variable $default_clang_id ist nicht definiert

### ISSUE THREAD

**Issue by eaCe** [TobiasKrais/multinewsletter#52]
Die Variable `$default_clang_id` ist nicht definiert, ebenso fehlt `default_test_sprache` in der yml.

![grafik](https://user-images.githubusercontent.com/2708231/233328998-11774395-84a6-42b1-b991-0ab1de9c6302.png)

**Comment by TobiasKrais** [comment]
Sollte in Version 3.5.2 nicht mehr vorkommen. Kannst du das prüfen?

**Comment by TobiasKrais** [comment]
`default_test_sprache` muss aus Redaxo ausgelesen werden und kann deshalb nicht in die YML rein.

**Comment by eaCe** [comment]
Alles gut, entschuldige die Störung :)

**Comment by TobiasKrais** [comment]
Kein Problem!
