### ISSUE TITLE
Platzhalter werden nicht ersetzt: +++GRAD+++ +++FIRSTNAME+++ +++LASTNAME+++ +++EMAIL+++

### ISSUE THREAD

**Issue by steri-rex** [TobiasKrais/multinewsletter#53]
Die Platzhalter +++GRAD+++ +++FIRSTNAME+++ +++LASTNAME+++ +++EMAIL+++ werden im Textkörper des Newsletters nicht ersetzt - stattdessen wird gar kein Text ausgegeben.
Alle anderen Platzhalter wie +++TITLE++ +++NEWSLETTERLINK+++ usw. werden jedoch richtig ersetzt.

Multinewsletter v. 3.5.4

**Comment by TobiasKrais** [comment]
Ich kann das Verhalten nicht nachvollziehen. Kannst du mal versuchen die aktuelle Git Version zu ziehen und auf den Server zu laden. Ist das dann immernoch so?

**Comment by steri-rex** [comment]
Danke für die Antwort - hab die aktuelle Git Version versucht aber auch hier das gleiche.
Es funktioniert nur dieser erste Teil
$replaces = [
            '+++GRAD+++' => $user->grad,
            '+++FIRSTNAME+++' => $user->firstname,
            '+++LASTNAME+++' => $user->lastname,
            '+++EMAIL+++' => $user->email,
        ];
von dieser Funktion nicht
https://github.com/TobiasKrais/multinewsletter/blob/44118e8675fa31967b0381742b7cf0635ac88841/lib/MultinewsletterNewsletter.php#L208
nicht - die Ersetzungen darunter mit +++TITLE+++ funktionieren.

Ich verwende PHP 8.1 und Redaxo 5.15.1

**Comment by TobiasKrais** [comment]
Da bist du an der richtigen Methode dran. Kannst du das bitte weiter debuggen? Ich kann die Situation nicht nachstellen.

**Comment by TobiasKrais** [comment]
Noch eine Frage: ändert sich das Verhalten, wenn du in den Einstellungen des Addons die Methode wie der Artikel gelesen wird änderst?

**Comment by steri-rex** [comment]
ja tatsächlich bei "redaxo intern" statt "socket" funktioniert es

**Comment by TobiasKrais** [comment]
Kannst du den Commit von eben bitte testen? (https://github.com/TobiasKrais/multinewsletter/commit/0db08d43728f5a444369369c48cf462e5552ab2e). Damit müsste der Fehler behoben sein.

**Comment by steri-rex** [comment]
ja funktioniert nun auch mit "Socket" - vielen Dank!

**Comment by TobiasKrais** [comment]
Danke fürs Testen. Ich mach gleich die Version 3.5.5 fertig.
