### ISSUE TITLE
Neutrale Anrede zulassen

### ISSUE THREAD

**Issue by thorol** [TobiasKrais/multinewsletter#55]
Es wäre gut, wenn man ebenfalls einen Anrede hätte, die neutral wäre. Oftmals werden aus Datenschutzgründen nicht die Anrede abgefragt. Die Multinewsletter Factory braucht jedoch einen integer. Ich habe diesen Integer auf -1 gesetzt für unbekannt, jedoch bekomme ich dann Deprecated-Meldungen bzgl. der Textersetzung. 
Es wäre sinnvoll auch eine neutrale Anrede zuzulassen, so dass man in der Datenbank auch sehen kann, dass dieser keine Anrede ausgefüllt hat. Ansonsten sind alle entweder weiblich oder männlich.

**Comment by TobiasKrais** [comment]
Welche Anreden sollten hinzugefügt werden?

**Comment by thorol** [comment]
Für mich wäre es erstmals in Ordnung, wenn "keine Anrede" aufgenommen werden würde. Evtl. würde ich dann in diesem Schritt noch divers aufnehmen. Ich weiß jedoch nicht, wie sich das rechtlich verhält. Aus diesem Grund frage ich erst gar keine Anrede ab.

**Comment by TobiasKrais** [comment]
Danke für die schnelle Antwort. Wenn wir das anpacken, dann richtig. Kannst du dich da mal schlau machen?

**Comment by TobiasKrais** [comment]
Thomas,
die Anrede Mx. könnte unsere Lösung sein. Ich habe mal einen Commit gemacht: https://github.com/TobiasKrais/multinewsletter/commit/80e7634ccc8484a8045b576dcb48e2a91d8bdd5d. Kannst du dir bitte die aktuelle Git Version ziehen und testen, ob das deinen Wünschen entspricht? Bitte reinstalliere das Addon nach dem Upload und lege in den Einstellungen die Übersetzungen der beiden neuen Felder fest.

**Comment by thorol** [comment]
Alles klar, Tobias, ich schau es mir an, kann evtl. etwas dauern, die Woche ist voll. VG Thomas

**Comment by TobiasKrais** [comment]
Danke dir. Eilt nicht.

**Comment by thorol** [comment]
In der Testmail sollte es noch die richtigen Anreden geben: 
![image](https://github.com/TobiasKrais/multinewsletter/assets/25980352/baf11dd5-5eb6-4cf6-a751-3f7a6672fb9e)

**Comment by TobiasKrais** [comment]
Ist jetzt auch drin (https://github.com/TobiasKrais/multinewsletter/commit/7fa85fbc3c9dbd17a2ecf4c4f83b04f18c5d1e59). Passt es sonst soweit?

**Comment by thorol** [comment]
Sonst hat es gepasst. Danke

**Comment by TobiasKrais** [comment]
Perfekt. Danke dir für deine Hilfe. Wird mit der nächsten Version veröffentlicht.
