### ISSUE TITLE
Falsche URL bei AKTIVIERUNGSLINK, wenn Redaxo im Unterordner liegt

### ISSUE THREAD

**Issue by godsdog** [TobiasKrais/multinewsletter#7]
Hey wenn Redaxo im Unterordner läuft, wird der Aktivierungslink nicht korrekt generiert.
Das Unterverzeichnis wird 2 x mal in den Link reingehängt.

In der Datei: multinewsletter/lib/multinewsletter_user.php habe ich folgendes gefixt:

Bei ca. Zeile 238 (habe davor Anpassungen gemacht, weiß nicht ob die Zeile ganz passt):
`$subscribe_link = rex_yrewrite::getFullUrlByArticleId($addon->getConfig('link'), $this->clang_id, array('activationkey' => $this->activationkey, 'email' => rawurldecode($this->email)));`

 **rex_yrewrite::getFullUrlByArticleId** hat's gebracht :)

**Comment by TobiasKrais** [comment]
Danke für den Hinweis. Wegen dem einen Punkt will ich eigentlich nicht die Abhängigkeit zu YRewrite erstellen. Hast du einen Vorschlag wie man das mit Redaxo Bordmitteln erstellen kann und könntest mir dann einen Pull Request erstellen?
